### ISSUE TITLE
Documenting all the dialogs that are still in Japanese.

### ISSUE THREAD

**Issue by xYuunaX** [yosh778/YsVIII-tools#4]
Will be posting pictures/screenshots of places where Japanese dialogs is still found.

Help wanted: if you can find where these strings are located, please provide information.
Thanks!

https://imgur.com/a/mnIO0

OCR'd into text format:
https://imgur.com/a/JssSH

**Comment by yosh778** [comment]
Swapping the forgotten system.bin file should fix all of those (found corresponding english in it)
